import type { IndustryPageProps } from '@/components/sections/IndustryPageTemplate'

type IndustryData = Omit<IndustryPageProps, 'breadcrumbs'>

export const industriesData: Record<string, IndustryData> = {
  doctors: {
    slug: 'doctors',
    industry: 'Doctors & Clinics',
    title: 'SEO for Doctors & Medical Clinics',
    headline: 'Digital Marketing for Doctors That Fills Your Appointment Calendar',
    subheadline: 'Help patients find your clinic online. We specialise in medical SEO, Google Ads for healthcare and reputation management that builds trust with prospective patients.',
    description: 'Specialised digital marketing for doctors and medical clinics — SEO, local SEO, Google Ads and reputation management.',
    challenges: [
      'Patients searching for doctors online but not finding your clinic',
      'Competitors outranking you on Google Maps and search',
      'Low volume of positive online reviews despite great patient care',
      'Website that doesn\'t convert visitors into booked appointments',
      'Google Ads compliance issues with medical advertising policies',
    ],
    solutions: [
      { icon: '🔍', title: 'Medical SEO', desc: 'Rank for high-intent local search terms like "doctor in [city]" and "[specialty] near me".' },
      { icon: '📍', title: 'Google Maps Dominance', desc: 'Optimise your Google Business Profile to appear in the local 3-pack for medical searches.' },
      { icon: '⭐', title: 'Review Management', desc: 'Build a steady stream of positive patient reviews that improve rankings and trust.' },
      { icon: '💻', title: 'Medical Website Design', desc: 'Professional, trust-building websites with appointment booking integration.' },
      { icon: '📱', title: 'Healthcare PPC', desc: 'HIPAA-compliant Google Ads campaigns that bring in new patients efficiently.' },
      { icon: '📧', title: 'Patient Retention', desc: 'Email and SMS marketing to keep existing patients engaged and coming back.' },
    ],
    results: [
      { metric: '3-5×', label: 'More New Patients' },
      { metric: '4.8★', label: 'Avg Review Rating' },
      { metric: '#1', label: 'Google Maps Rank' },
      { metric: '60%', label: 'Lower Cost Per Patient' },
    ],
    faqs: [
      { q: 'Can doctors advertise on Google?', a: 'Yes. Doctors can advertise on Google Ads, but healthcare advertising has specific policies around sensitive health categories. We ensure full compliance with all Google healthcare advertising policies.' },
      { q: 'How long does medical SEO take?', a: 'Most of our medical clients see meaningful improvement in local rankings within 2–3 months, with significant patient volume increase by month 6.' },
      { q: 'Do you handle HIPAA compliance?', a: 'We take privacy seriously and work within healthcare compliance requirements for all marketing activities including forms, ad copy and landing pages.' },
    ],
    services: [
      { label: 'Local SEO', href: '/services/local-seo' },
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Website Design', href: '/services/website-design' },
      { label: 'ORM', href: '/services/orm' },
    ],
  },
  dentists: {
    slug: 'dentists',
    industry: 'Dentists',
    title: 'SEO for Dentists & Dental Clinics',
    headline: 'Dental Marketing That Brings New Patients to Your Chair',
    subheadline: 'Grow your dental practice with proven digital marketing strategies. More Google visibility, more reviews, more patients — all from one trusted agency.',
    description: 'Digital marketing services for dentists including local SEO, Google Ads and reputation management.',
    challenges: [
      'New patients not finding your dental practice online',
      'Competing with large dental chains and DSOs',
      'Inconsistent patient flow — busy one month, slow the next',
      'Negative reviews affecting your reputation',
      'Wasting money on generic advertising that doesn\'t reach dental patients',
    ],
    solutions: [
      { icon: '🦷', title: 'Dental SEO', desc: 'Rank for searches like "dentist in [city]", "teeth whitening near me" and more.' },
      { icon: '📍', title: 'Local Pack Rankings', desc: 'Get into the Google Maps 3-pack where most new dental patients click.' },
      { icon: '⭐', title: 'Review Generation', desc: 'Automated review request system to build your 5-star reputation.' },
      { icon: '💻', title: 'Dental Website Design', desc: 'Patient-converting dental websites with before/after galleries and booking forms.' },
      { icon: '📈', title: 'Google Ads for Dentists', desc: 'Target high-value procedures like implants, Invisalign and whitening.' },
      { icon: '🔄', title: 'Patient Reactivation', desc: 'Email campaigns that bring back lapsed patients for check-ups and treatments.' },
    ],
    results: [
      { metric: '40+', label: 'New Patients/Month' },
      { metric: '4.9★', label: 'Average Rating' },
      { metric: '3×', label: 'Website Traffic' },
      { metric: '50%', label: 'Lower CPL vs Ads' },
    ],
    faqs: [
      { q: 'What digital marketing works best for dentists?', a: 'Local SEO and Google Maps optimisation consistently delivers the best ROI for dental practices. Google Ads works well for high-value treatments like implants. The combination of both is the most powerful approach.' },
      { q: 'How do I get more dental patients online?', a: 'The most effective strategy combines ranking on Google Maps, having an excellent website that converts visitors, and maintaining a strong review profile with 4.5+ stars.' },
    ],
    services: [
      { label: 'Local SEO', href: '/services/local-seo' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Website Design', href: '/services/website-design' },
      { label: 'ORM', href: '/services/orm' },
    ],
  },
  'real-estate': {
    slug: 'real-estate',
    industry: 'Real Estate',
    title: 'SEO for Real Estate Agents & Developers',
    headline: 'Real Estate Digital Marketing That Generates Qualified Buyer & Seller Leads',
    subheadline: 'Stand out in a crowded market. We help real estate agents and developers dominate local search, generate consistent leads and close more deals.',
    description: 'Real estate digital marketing including SEO, Google Ads, lead generation and website development.',
    challenges: [
      'High competition from large portals like 99acres, MagicBricks and Housing.com',
      'Expensive Google Ads with low-quality leads',
      'Website not generating any organic inquiries',
      'No consistent strategy for generating buyer or seller leads',
      'Poor local search visibility for property-related keywords',
    ],
    solutions: [
      { icon: '🏠', title: 'Real Estate SEO', desc: 'Rank for high-intent property searches in your target locations.' },
      { icon: '📍', title: 'Local Lead Gen', desc: 'Target buyers and sellers in specific localities and property segments.' },
      { icon: '💰', title: 'Targeted Google Ads', desc: 'Property-specific campaigns targeting buyers at key decision stages.' },
      { icon: '💻', title: 'Property Website Design', desc: 'Powerful listing websites with search, filters and lead capture.' },
      { icon: '📱', title: 'Social Media Marketing', desc: 'Showcase properties and build a brand that buyers trust.' },
      { icon: '📧', title: 'Lead Nurturing', desc: 'Email automations to nurture leads over the long decision cycle.' },
    ],
    results: [
      { metric: '5×', label: 'More Inquiries' },
      { metric: '60%', label: 'Lower Lead Cost' },
      { metric: '#1', label: 'Local Rankings' },
      { metric: '2×', label: 'Qualified Viewings' },
    ],
    faqs: [
      { q: 'How do real estate agents get more leads online?', a: 'The most effective combination is Local SEO to rank for property searches in your area, Google Ads for high-intent buyer and seller queries, and a landing page strategy that captures leads efficiently.' },
    ],
    services: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Lead Generation', href: '/services/lead-generation' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Website Design', href: '/services/website-design' },
    ],
  },
  ecommerce: {
    slug: 'ecommerce',
    industry: 'E-commerce',
    title: 'SEO & Digital Marketing for E-commerce',
    headline: 'E-commerce Marketing That Drives More Sales & Higher Margins',
    subheadline: 'Reduce your dependence on paid ads and grow your online store with multi-channel digital marketing strategies that scale profitably.',
    description: 'E-commerce digital marketing including SEO, Google Shopping, Meta Ads and email marketing.',
    challenges: [
      'Over-reliance on paid ads eating into margins',
      'Product pages not ranking on Google',
      'High cart abandonment rate',
      'Difficulty standing out from Amazon and Flipkart',
      'No organic traffic strategy to compound growth',
    ],
    solutions: [
      { icon: '🛒', title: 'E-commerce SEO', desc: 'Rank product and category pages for high-intent buyer keywords.' },
      { icon: '🛍️', title: 'Google Shopping', desc: 'Get your products into Google Shopping results with optimised feeds.' },
      { icon: '📧', title: 'Email Automation', desc: 'Abandoned cart, welcome and post-purchase sequences that drive revenue.' },
      { icon: '📱', title: 'Meta Shopping Ads', desc: 'Dynamic product ads on Instagram and Facebook targeting your buyers.' },
      { icon: '🔄', title: 'Retention Marketing', desc: 'Loyalty programs and remarketing to maximise customer lifetime value.' },
      { icon: '📊', title: 'Analytics & Attribution', desc: 'GA4 e-commerce tracking with full multi-channel attribution.' },
    ],
    results: [
      { metric: '9×', label: 'Revenue Growth' },
      { metric: '6.5×', label: 'Average ROAS' },
      { metric: '45%', label: 'Lower CAC' },
      { metric: '3×', label: 'Organic Traffic' },
    ],
    faqs: [
      { q: 'How do I increase e-commerce sales with digital marketing?', a: 'The most effective e-commerce strategy combines SEO for organic traffic, Google Shopping for transactional queries, Meta Ads for discovery and email marketing for retention and lifecycle revenue.' },
    ],
    services: [
      { label: 'E-commerce SEO', href: '/services/ecommerce-seo' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Email Marketing', href: '/services/email-marketing' },
      { label: 'Shopify Development', href: '/services/shopify-development' },
    ],
  },
  saas: {
    slug: 'saas',
    industry: 'SaaS & Tech',
    title: 'SEO & Digital Marketing for SaaS Companies',
    headline: 'SaaS Digital Marketing That Reduces CAC and Grows MRR',
    subheadline: 'Content-led SEO, product-led growth and full-funnel paid campaigns — the complete digital marketing system for SaaS companies.',
    description: 'Specialised digital marketing for SaaS companies focused on reducing CAC, growing MRR and scaling organic traffic.',
    challenges: [
      'High CAC from Google Ads not sustainable at scale',
      'Struggling to rank for competitive SaaS keywords',
      'Long sales cycles with complex B2B buying journeys',
      'Churn reducing the impact of acquisition campaigns',
      'No content-led SEO strategy building long-term organic moat',
    ],
    solutions: [
      { icon: '📝', title: 'Content-Led SEO', desc: 'Build an organic acquisition engine with strategic content clusters and bottom-of-funnel pages.' },
      { icon: '🎯', title: 'B2B Google Ads', desc: 'High-intent keyword campaigns targeting users actively evaluating SaaS solutions.' },
      { icon: '🔗', title: 'Link Building', desc: 'Digital PR and partnerships to build domain authority in your category.' },
      { icon: '🔄', title: 'Retention Email Marketing', desc: 'Onboarding sequences, feature adoption emails and re-engagement campaigns.' },
      { icon: '📊', title: 'Product Analytics Integration', desc: 'GA4 + Mixpanel integration for full-funnel visibility from ad click to retention.' },
      { icon: '💡', title: 'Comparison Page SEO', desc: 'Target "[Your Product] vs Competitor" searches to win evaluation-stage traffic.' },
    ],
    results: [
      { metric: '4×', label: 'Organic Trial Signups' },
      { metric: '40%', label: 'Lower CAC' },
      { metric: '3×', label: 'MQL Volume' },
      { metric: '25%', label: 'Churn Reduction' },
    ],
    faqs: [
      { q: 'What SEO strategy works best for SaaS?', a: 'SaaS SEO should focus on three areas: landing pages for your core keywords, comparison and alternative pages targeting evaluation-stage searches, and a blog content strategy targeting problems your software solves.' },
    ],
    services: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Content Marketing', href: '/services/content-marketing' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Email Marketing', href: '/services/email-marketing' },
    ],
  },
  'law-firms': {
    slug: 'law-firms',
    industry: 'Law Firms',
    title: 'SEO & Digital Marketing for Law Firms',
    headline: 'Law Firm Marketing That Generates Consistent, High-Quality Client Inquiries',
    subheadline: 'Dominate Google search for legal services in your practice area and location. Build the credibility and online presence that serious legal clients look for.',
    description: 'Specialised digital marketing for law firms including legal SEO, Google Ads and website design.',
    challenges: [
      'Ranking against large law directories like Justia and FindLaw',
      'High CPC for legal keywords on Google Ads',
      'Clients not trusting firms without strong reviews and authority',
      'No consistent content strategy to demonstrate legal expertise',
      'Website not converting visitors into consultation bookings',
    ],
    solutions: [
      { icon: '⚖️', title: 'Legal SEO', desc: 'Rank for high-intent queries like "[practice area] lawyer in [city]".' },
      { icon: '📝', title: 'Legal Content Strategy', desc: 'Expert articles and guides that demonstrate authority and rank for legal questions.' },
      { icon: '⭐', title: 'Reputation Management', desc: 'Build a strong review profile on Google and legal directories.' },
      { icon: '💻', title: 'Law Firm Website', desc: 'Professional, trust-building websites with consultation booking forms.' },
      { icon: '🎯', title: 'Legal PPC', desc: 'Targeted Google Ads for high-value practice areas with strong conversion tracking.' },
      { icon: '🔗', title: 'Legal Directory Citations', desc: 'Build citations on Avvo, Justia, Martindale and other legal directories.' },
    ],
    results: [
      { metric: '30+', label: 'Inquiries/Month' },
      { metric: '#1', label: 'Local Rankings' },
      { metric: '4×', label: 'More Website Traffic' },
      { metric: '60%', label: 'Lower CPL' },
    ],
    faqs: [
      { q: 'What is the best marketing strategy for law firms?', a: 'Local SEO combined with a strong content strategy is the most cost-effective long-term approach for law firms. Google Ads works for immediate results but requires careful targeting to manage CPCs for legal keywords.' },
    ],
    services: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Local SEO', href: '/services/local-seo' },
      { label: 'Content Marketing', href: '/services/content-marketing' },
      { label: 'Website Design', href: '/services/website-design' },
    ],
  },
  'small-business': {
    slug: 'small-business',
    industry: 'Small Businesses',
    title: 'Digital Marketing for Small Businesses',
    headline: 'Affordable Digital Marketing That Helps Small Businesses Compete and Win',
    subheadline: 'You don\'t need a big budget to make a big impact online. Our small business digital marketing strategies are designed to deliver maximum ROI on every rupee you spend.',
    description: 'Affordable, results-driven digital marketing services for small businesses — SEO, local SEO, Google Ads and website design.',
    challenges: [
      'Limited budget competing against larger competitors',
      'Not knowing which digital channels to invest in first',
      'Lack of time to manage marketing alongside running the business',
      'Website that doesn\'t generate any leads or calls',
      'No local search presence despite being a great local business',
    ],
    solutions: [
      { icon: '🏪', title: 'Local SEO', desc: 'Get found by local customers searching for your services on Google and Maps.' },
      { icon: '💰', title: 'Budget-Smart PPC', desc: 'Laser-targeted Google Ads campaigns that maximise every rupee of ad spend.' },
      { icon: '💻', title: 'Simple, Effective Website', desc: 'Fast, conversion-focused websites that generate real inquiries.' },
      { icon: '📱', title: 'Social Media Presence', desc: 'Build a consistent social presence that keeps your brand top of mind.' },
      { icon: '⭐', title: 'Review Generation', desc: 'Automated review campaigns that build trust and improve local rankings.' },
      { icon: '📧', title: 'Email Marketing', desc: 'Simple automations to stay in touch with customers and drive repeat business.' },
    ],
    results: [
      { metric: '3×', label: 'More Online Leads' },
      { metric: '2×', label: 'Website Traffic' },
      { metric: '4.8★', label: 'Review Rating' },
      { metric: '25%', label: 'Lower Marketing Costs' },
    ],
    faqs: [
      { q: 'What is the best digital marketing for small businesses?', a: 'For most small businesses, Local SEO and Google Business Profile optimisation delivers the best ROI. It helps you get found by local customers at the exact moment they\'re searching for what you offer.' },
      { q: 'Can I afford digital marketing on a small budget?', a: 'Absolutely. We have packages starting from ₹10,000/month designed specifically for small businesses. We focus on the channels that deliver the best ROI for your specific situation.' },
    ],
    services: [
      { label: 'Local SEO', href: '/services/local-seo' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Website Design', href: '/services/website-design' },
      { label: 'Social Media Marketing', href: '/services/social-media-marketing' },
    ],
  },
  startups: {
    slug: 'startups',
    industry: 'Startups',
    title: 'Digital Marketing for Startups',
    headline: 'Startup Digital Marketing Built for Speed, Scale and Capital Efficiency',
    subheadline: 'Build your growth engine early. We help startups acquire their first 100, 1,000 and 10,000 customers with cost-efficient digital marketing strategies.',
    description: 'Growth-focused digital marketing for startups — channel strategy, SEO, content marketing and paid acquisition.',
    challenges: [
      'Limited runway requiring capital-efficient customer acquisition',
      'Building brand awareness from zero in a competitive market',
      'Unclear on which acquisition channels to prioritise',
      'Product-market fit unclear — needing fast testing and iteration',
      'No time or in-house expertise to build growth systems',
    ],
    solutions: [
      { icon: '🚀', title: 'Growth Strategy', desc: 'Define your north-star metric and build a channel strategy around it.' },
      { icon: '📝', title: 'Content-Led SEO', desc: 'Build an organic acquisition moat with strategic content and SEO.' },
      { icon: '🧪', title: 'Rapid Experimentation', desc: 'Test multiple channels quickly to identify what works for your business.' },
      { icon: '💰', title: 'Paid Acquisition', desc: 'Google and Meta Ads with full funnel tracking to optimise CAC/LTV.' },
      { icon: '🔗', title: 'PR & Backlinks', desc: 'Build brand credibility and domain authority through digital PR.' },
      { icon: '📊', title: 'Analytics Foundation', desc: 'GA4 + Mixpanel setup for data-driven decisions from day one.' },
    ],
    results: [
      { metric: '10×', label: 'User Growth' },
      { metric: '60%', label: 'Lower CAC' },
      { metric: '5×', label: 'Organic Traffic' },
      { metric: '3×', label: 'Trial Conversions' },
    ],
    faqs: [
      { q: 'When should a startup start investing in digital marketing?', a: 'Ideally, start building your SEO and content foundation from day one. Paid channels can be tested earlier to validate channels and messaging before you scale spending.' },
      { q: 'How do startups get their first customers online?', a: 'The fastest path to first customers is usually a combination of SEO for product keywords, targeted LinkedIn outreach for B2B, or Meta/Google Ads for B2C with a tightly defined target audience.' },
    ],
    services: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Content Marketing', href: '/services/content-marketing' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Digital Marketing Consulting', href: '/services/digital-marketing-consulting' },
    ],
  },
}

export function getIndustryData(slug: string): IndustryData | null {
  return industriesData[slug] ?? null
}
