import type { ServicePageProps } from '@/components/sections/ServicePageTemplate'
import { siteConfig } from './metadata'

type ServiceData = Omit<ServicePageProps, 'breadcrumbs'>

export const servicesData: Record<string, ServiceData> = {
  seo: {
    slug: 'seo',
    title: 'SEO Services',
    headline: 'SEO Services That Drive Real Organic Growth',
    subheadline: 'Stop paying for every click. Our data-driven SEO strategies put your website on page 1 of Google — and keep it there.',
    description: 'Comprehensive SEO services including technical SEO, on-page optimization, link building and content strategy.',
    benefits: [
      { icon: '📈', title: 'More Organic Traffic', desc: 'Consistent, compounding traffic that doesn\'t stop when you stop paying.' },
      { icon: '🎯', title: 'Qualified Leads', desc: 'Attract people actively searching for what you offer — higher intent, better conversion.' },
      { icon: '💰', title: 'Best ROI in Digital', desc: 'SEO delivers the highest long-term ROI of any digital marketing channel.' },
      { icon: '🏆', title: 'Outrank Competitors', desc: 'Dominate search results and make it hard for competitors to be found.' },
      { icon: '🔬', title: 'Technical Excellence', desc: 'We fix the technical issues that hold your site back from ranking.' },
      { icon: '📊', title: 'Measurable Results', desc: 'Clear reporting on rankings, traffic, leads and revenue impact.' },
    ],
    includes: [
      'Comprehensive SEO audit & competitor analysis',
      'Keyword research & content strategy',
      'On-page SEO optimisation (meta, headings, content)',
      'Technical SEO (speed, Core Web Vitals, schema)',
      'Link building & digital PR',
      'Local SEO (if applicable)',
      'Monthly performance reporting',
      'Google Search Console & Analytics setup',
      'Content creation & optimisation',
      'Ongoing strategy sessions',
    ],
    process: [
      { step: '01', title: 'SEO Audit', desc: 'Complete technical and content audit of your current site.' },
      { step: '02', title: 'Strategy Build', desc: 'Custom keyword strategy and content roadmap.' },
      { step: '03', title: 'On-Page & Technical', desc: 'Optimise every page and fix all technical issues.' },
      { step: '04', title: 'Link Building', desc: 'High-quality backlinks to boost authority and rankings.' },
    ],
    tools: ['Ahrefs', 'Semrush', 'Google Search Console', 'Screaming Frog', 'Google Analytics 4', 'Surfer SEO', 'Clearscope', 'PageSpeed Insights'],
    faqs: [
      { q: 'How long does SEO take to show results?', a: 'Most clients see meaningful movement within 3–6 months, with significant results by 9–12 months. SEO is a long-term investment with compounding returns.' },
      { q: 'Do you guarantee SEO rankings?', a: 'No ethical SEO agency can guarantee specific rankings (Google\'s algorithm is constantly changing). We do guarantee our process, transparency, and relentless effort to improve your rankings.' },
      { q: 'What is included in your SEO services?', a: 'Our SEO service includes technical SEO, on-page optimisation, keyword research, content strategy, link building, monthly reporting and strategy calls.' },
      { q: 'How much does SEO cost?', a: 'Our SEO packages start from ₹15,000/month. The cost depends on your industry, competition level and goals. We\'ll give you a custom quote on a free strategy call.' },
    ],
    relatedServices: [
      { label: 'Local SEO', href: '/services/local-seo' },
      { label: 'Technical SEO', href: '/services/technical-seo' },
      { label: 'E-commerce SEO', href: '/services/ecommerce-seo' },
      { label: 'Content Marketing', href: '/services/content-marketing' },
      { label: 'Google Ads', href: '/services/google-ads' },
    ],
  },
  'local-seo': {
    slug: 'local-seo',
    title: 'Local SEO Services',
    headline: 'Local SEO Services That Put You on the Map',
    subheadline: 'Get found by customers in your city. Our Local SEO strategies ensure you dominate Google Maps, local search results and "near me" queries.',
    description: 'Local SEO services to help businesses rank in their city for relevant searches and dominate Google Maps.',
    benefits: [
      { icon: '📍', title: 'Google Maps Visibility', desc: 'Appear in the Google Maps 3-pack for high-intent local searches.' },
      { icon: '📱', title: 'Mobile Search Ready', desc: '78% of local mobile searches lead to offline purchases. We capture that traffic.' },
      { icon: '⭐', title: 'More 5-Star Reviews', desc: 'We help you generate and manage reviews that build trust and boost rankings.' },
      { icon: '🏘️', title: 'City-Specific Rankings', desc: 'Rank for targeted location + service keyword combinations.' },
      { icon: '📞', title: 'More Calls & Walk-ins', desc: 'Direct phone calls and directions from local customers ready to buy.' },
      { icon: '🎯', title: 'Hyper-Targeted Traffic', desc: 'Reach only the customers who are near you and looking for your services.' },
    ],
    includes: [
      'Google Business Profile optimisation & management',
      'Local keyword research & mapping',
      'NAP consistency audit & citation building',
      'Local on-page SEO (city pages, location schema)',
      'Review generation & reputation management',
      'Local link building',
      'Google Maps ranking optimisation',
      'Monthly local SEO reporting',
    ],
    process: [
      { step: '01', title: 'GBP Audit', desc: 'Full audit of your Google Business Profile and local presence.' },
      { step: '02', title: 'Citation Cleanup', desc: 'Fix inconsistent NAP data across all directories.' },
      { step: '03', title: 'Local Optimisation', desc: 'Optimise GBP, website and local content.' },
      { step: '04', title: 'Review & Links', desc: 'Build reviews and local citations to boost Maps rankings.' },
    ],
    tools: ['Brightlocal', 'Google Business Profile', 'Whitespark', 'Semrush Local', 'Moz Local', 'Ahrefs'],
    faqs: [
      { q: 'What is Local SEO?', a: 'Local SEO is the practice of optimising your online presence to attract customers from local searches on Google and Google Maps.' },
      { q: 'How do I rank on Google Maps?', a: 'Google Maps rankings are driven by relevance, distance and prominence. We optimise your Google Business Profile, build citations and generate reviews to improve all three factors.' },
      { q: 'How long does Local SEO take?', a: 'Typically 2–4 months to see meaningful improvement in Google Maps rankings, faster than organic SEO.' },
    ],
    relatedServices: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Technical SEO', href: '/services/technical-seo' },
      { label: 'ORM', href: '/services/orm' },
    ],
  },
  'technical-seo': {
    slug: 'technical-seo',
    title: 'Technical SEO Services',
    headline: 'Technical SEO That Unlocks Your Site\'s Full Ranking Potential',
    subheadline: 'Even the best content won\'t rank if your website has technical issues. We fix the foundation so Google can crawl, index and rank your site.',
    description: 'Expert technical SEO services to fix crawlability, site speed, Core Web Vitals and indexation issues.',
    benefits: [
      { icon: '⚡', title: 'Faster Site Speed', desc: 'We optimise Core Web Vitals — LCP, FID, CLS — for both rankings and user experience.' },
      { icon: '🕷️', title: 'Better Crawlability', desc: 'Ensure search engine bots can efficiently crawl and index every important page.' },
      { icon: '🔒', title: 'HTTPS & Security', desc: 'Secure site configuration with proper redirects, SSL and no mixed content.' },
      { icon: '🏗️', title: 'Site Architecture', desc: 'Logical URL structure, internal linking and silo architecture for maximum authority flow.' },
      { icon: '📱', title: 'Mobile Optimisation', desc: 'Mobile-first indexing compliant with fast, responsive pages on all devices.' },
      { icon: '🗂️', title: 'Schema Markup', desc: 'Structured data that triggers rich results and SERP features.' },
    ],
    includes: [
      'Full technical SEO audit (200+ checkpoints)',
      'Core Web Vitals optimisation',
      'XML sitemap & robots.txt optimisation',
      'Structured data / schema markup implementation',
      'Canonical tags & duplicate content resolution',
      'Redirect audit & fix (3xx, 4xx, 5xx)',
      'Crawl budget optimisation',
      'Hreflang implementation (if multilingual)',
      'Mobile usability improvements',
      'Page speed optimisation',
    ],
    process: [
      { step: '01', title: 'Technical Audit', desc: 'Comprehensive crawl and analysis of all technical issues.' },
      { step: '02', title: 'Prioritisation', desc: 'Issues ranked by impact on rankings and traffic.' },
      { step: '03', title: 'Implementation', desc: 'We fix issues or provide developer-ready specifications.' },
      { step: '04', title: 'Validation', desc: 'Re-crawl and testing to confirm all fixes are in place.' },
    ],
    tools: ['Screaming Frog', 'Google Search Console', 'GTmetrix', 'PageSpeed Insights', 'Ahrefs', 'Semrush', 'Chrome DevTools', 'Schema.org validator'],
    faqs: [
      { q: 'What is technical SEO?', a: 'Technical SEO refers to optimising the backend and infrastructure of your website so search engines can crawl, index and rank it effectively.' },
      { q: 'How do I know if my site has technical SEO issues?', a: 'Signs include slow load times, pages not indexed, manual actions in Search Console, poor Core Web Vitals scores, or content that simply won\'t rank despite good backlinks.' },
    ],
    relatedServices: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Website Development', href: '/services/website-development' },
      { label: 'E-commerce SEO', href: '/services/ecommerce-seo' },
    ],
  },
  'ecommerce-seo': {
    slug: 'ecommerce-seo',
    title: 'E-commerce SEO Services',
    headline: 'E-commerce SEO That Drives Sales, Not Just Traffic',
    subheadline: 'Rank your product and category pages for high-intent buyer keywords. More organic visibility means lower customer acquisition cost and higher profit margins.',
    description: 'Specialised e-commerce SEO services for Shopify, WooCommerce and custom stores to increase product visibility and sales.',
    benefits: [
      { icon: '🛒', title: 'Product Page Rankings', desc: 'Optimise every product page to rank for transactional buyer keywords.' },
      { icon: '🏷️', title: 'Category Page SEO', desc: 'Powerful category page optimisation that captures high-volume keyword traffic.' },
      { icon: '💸', title: 'Lower CAC', desc: 'Replace expensive paid ads with free organic traffic to reduce cost per acquisition.' },
      { icon: '🔎', title: 'Rich Snippets', desc: 'Product schema, review stars and prices in search results for higher CTR.' },
      { icon: '🔄', title: 'Internal Linking', desc: 'Strategic internal link structure that passes authority to your money pages.' },
      { icon: '📊', title: 'Revenue Attribution', desc: 'Clear reporting on SEO-driven revenue and ROI.' },
    ],
    includes: [
      'E-commerce SEO audit',
      'Product & category keyword research',
      'On-page optimisation for product & category pages',
      'Product schema / structured data',
      'Faceted navigation SEO fix',
      'Duplicate content resolution',
      'Internal linking strategy',
      'Blog/content strategy for top-of-funnel traffic',
      'Monthly e-commerce SEO reporting',
    ],
    process: [
      { step: '01', title: 'Store Audit', desc: 'Full technical and content audit of your e-commerce store.' },
      { step: '02', title: 'Keyword Mapping', desc: 'Map buyer keywords to every product and category page.' },
      { step: '03', title: 'Optimisation', desc: 'Implement on-page, technical and schema improvements.' },
      { step: '04', title: 'Content & Links', desc: 'Build topical authority and backlinks to category pages.' },
    ],
    tools: ['Ahrefs', 'Semrush', 'Screaming Frog', 'Shopify Analytics', 'Google Analytics 4', 'Google Search Console'],
    faqs: [
      { q: 'Does SEO work for e-commerce?', a: 'Absolutely. E-commerce SEO is one of the best long-term investments for online stores. It reduces reliance on paid ads and creates a sustainable, low-cost acquisition channel.' },
      { q: 'How do you handle large product catalogues?', a: 'We use category-level prioritisation, faceted navigation optimisation and systematic on-page templates to scale SEO across thousands of products.' },
    ],
    relatedServices: [
      { label: 'Shopify Development', href: '/services/shopify-development' },
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Google Ads', href: '/services/google-ads' },
    ],
  },
  'google-ads': {
    slug: 'google-ads',
    title: 'Google Ads (PPC) Services',
    headline: 'Google Ads Management That Maximises Every Rupee You Spend',
    subheadline: 'Stop wasting money on poorly managed Google Ads. Our certified PPC experts build and optimise campaigns that deliver qualified leads at the lowest possible cost.',
    description: 'Expert Google Ads management services to maximise ROI on your PPC campaigns.',
    benefits: [
      { icon: '⚡', title: 'Instant Traffic', desc: 'Go live today and start getting clicks and leads immediately.' },
      { icon: '🎯', title: 'Laser-Targeted Ads', desc: 'Target by keyword, location, device, time and audience for maximum relevance.' },
      { icon: '💰', title: 'Maximise ROAS', desc: 'We continuously optimise to squeeze the most revenue out of every ad dollar.' },
      { icon: '📊', title: 'Full Transparency', desc: 'You own your account. See every click, cost and conversion in real time.' },
      { icon: '🔬', title: 'A/B Testing', desc: 'Constant testing of ads, landing pages and audiences to keep improving performance.' },
      { icon: '📞', title: 'More Qualified Leads', desc: 'Quality score optimisation and negative keywords ensure only relevant clicks.' },
    ],
    includes: [
      'Google Ads account audit & setup',
      'Keyword research & negative keywords',
      'Campaign structure & ad group setup',
      'Compelling ad copy creation & A/B testing',
      'Landing page recommendations',
      'Conversion tracking setup (GA4 + GTM)',
      'Bid strategy optimisation (Smart Bidding)',
      'Audience targeting & remarketing',
      'Shopping campaigns (for e-commerce)',
      'Monthly performance reporting',
    ],
    process: [
      { step: '01', title: 'Account Audit', desc: 'Review current account structure, wasted spend and opportunities.' },
      { step: '02', title: 'Campaign Build', desc: 'Set up optimal campaign structure, ad groups and keywords.' },
      { step: '03', title: 'Launch & Monitor', desc: 'Launch campaigns with tight monitoring in the first 2 weeks.' },
      { step: '04', title: 'Optimise & Scale', desc: 'Weekly optimisation and scale what\'s working.' },
    ],
    tools: ['Google Ads', 'Google Analytics 4', 'Google Tag Manager', 'Google Keyword Planner', 'Optmyzr', 'SEMrush Advertising'],
    faqs: [
      { q: 'How much do I need to spend on Google Ads?', a: 'We recommend a minimum ad budget of ₹20,000–₹30,000/month to generate meaningful data and results. Our management fee is separate from your ad spend.' },
      { q: 'Can you manage my existing Google Ads account?', a: 'Yes. We offer account audits and takeovers. We\'ll review your current setup and give you a clear picture of what\'s working and what needs to change.' },
    ],
    relatedServices: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Social Media Marketing', href: '/services/social-media-marketing' },
      { label: 'CRO', href: '/services/cro' },
      { label: 'Lead Generation', href: '/services/lead-generation' },
    ],
  },
  'social-media-marketing': {
    slug: 'social-media-marketing',
    title: 'Social Media Marketing Services',
    headline: 'Social Media Marketing That Builds Brands & Drives Sales',
    subheadline: 'From strategy to content creation, community management and paid social — we handle your entire social media presence so you can focus on running your business.',
    description: 'Full-service social media marketing including content creation, community management and paid social campaigns.',
    benefits: [
      { icon: '💡', title: 'Brand Awareness', desc: 'Reach thousands of potential customers with scroll-stopping content every week.' },
      { icon: '❤️', title: 'Community Building', desc: 'Build a loyal fanbase that engages with your brand, recommends it and buys from you.' },
      { icon: '💸', title: 'Lead Generation', desc: 'Social media ads with precise targeting to fill your pipeline with qualified leads.' },
      { icon: '✍️', title: 'Content Creation', desc: 'Professional graphics, videos and captions created by our in-house team.' },
      { icon: '📊', title: 'Data-Driven Growth', desc: 'Weekly analysis of what\'s working. We double down on winning content types.' },
      { icon: '🔔', title: '24/7 Monitoring', desc: 'We monitor comments and DMs so your brand is always responsive.' },
    ],
    includes: [
      'Social media strategy & content calendar',
      'Profile optimisation (all platforms)',
      'Custom graphics & short-form video creation',
      'Caption writing & hashtag strategy',
      'Community management (comments & DMs)',
      'Instagram & Facebook advertising',
      'LinkedIn B2B campaigns (if applicable)',
      'Monthly performance reporting & strategy call',
    ],
    process: [
      { step: '01', title: 'Brand Audit', desc: 'Analyse your current social presence and competitors.' },
      { step: '02', title: 'Strategy', desc: 'Build content pillars, posting schedule and paid strategy.' },
      { step: '03', title: 'Create & Publish', desc: 'Design, write and schedule content across platforms.' },
      { step: '04', title: 'Grow & Optimise', desc: 'Track performance and double down on what drives results.' },
    ],
    tools: ['Meta Business Suite', 'Canva Pro', 'CapCut', 'Later', 'Hootsuite', 'Sprout Social', 'Facebook Ads Manager'],
    faqs: [
      { q: 'Which social media platforms do you manage?', a: 'We manage Instagram, Facebook, LinkedIn, Twitter/X, YouTube and Pinterest. We\'ll recommend the right platforms based on your audience and business goals.' },
      { q: 'Do you create the content or do I?', a: 'We handle everything — strategy, design, copywriting, scheduling and reporting. You just review and approve before posting.' },
    ],
    relatedServices: [
      { label: 'Content Marketing', href: '/services/content-marketing' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Branding', href: '/services/branding' },
    ],
  },
  'content-marketing': {
    slug: 'content-marketing',
    title: 'Content Marketing Services',
    headline: 'Content Marketing That Builds Authority & Drives Organic Growth',
    subheadline: 'Strategic, SEO-optimised content that attracts your ideal customers, builds trust and converts — at every stage of the funnel.',
    description: 'Full-service content marketing including strategy, creation, distribution and performance measurement.',
    benefits: [
      { icon: '🏆', title: 'Industry Authority', desc: 'Position your brand as the go-to expert in your field with high-value content.' },
      { icon: '📈', title: 'Organic Traffic Growth', desc: 'SEO-optimised content that ranks on Google and drives consistent free traffic.' },
      { icon: '🎯', title: 'Lead Generation', desc: 'Content funnels that capture leads at every stage of the buyer journey.' },
      { icon: '🔄', title: 'Compounding Returns', desc: 'Unlike ads that stop when you stop paying, great content works for years.' },
      { icon: '💡', title: 'Educate & Convert', desc: 'Answer customer questions, build trust and guide them to buy from you.' },
      { icon: '🔗', title: 'Earn Backlinks', desc: 'High-quality content naturally attracts links, boosting your overall SEO.' },
    ],
    includes: [
      'Content strategy & editorial calendar',
      'Keyword research & topic clustering',
      'Long-form blog posts (1,500–3,000 words)',
      'Landing page copywriting',
      'Email sequences & newsletters',
      'Social media content repurposing',
      'Infographics & visual assets',
      'Content performance reporting',
    ],
    process: [
      { step: '01', title: 'Content Audit', desc: 'Assess existing content and identify gaps and opportunities.' },
      { step: '02', title: 'Strategy & Calendar', desc: 'Build a topic cluster strategy mapped to your business goals.' },
      { step: '03', title: 'Create & Publish', desc: 'Write, design and publish SEO-optimised content.' },
      { step: '04', title: 'Promote & Track', desc: 'Distribute, build links and measure performance.' },
    ],
    tools: ['Surfer SEO', 'Clearscope', 'Ahrefs', 'Grammarly', 'Canva', 'WordPress', 'Google Docs'],
    faqs: [
      { q: 'How many blog posts do you write per month?', a: 'Packages typically include 4–8 long-form posts per month. We focus on quality over quantity — each post is fully SEO-optimised and strategically planned.' },
      { q: 'Who writes the content?', a: 'Our in-house team of experienced writers with backgrounds in digital marketing, SEO and your specific industry. All content goes through an editorial review before delivery.' },
    ],
    relatedServices: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Email Marketing', href: '/services/email-marketing' },
      { label: 'Social Media Marketing', href: '/services/social-media-marketing' },
    ],
  },
  'website-design': {
    slug: 'website-design',
    title: 'Website Design Services',
    headline: 'Website Design That Converts Visitors into Customers',
    subheadline: 'Beautiful, fast and conversion-optimised websites that make a powerful first impression and drive real business results.',
    description: 'Professional website design services that combine beautiful aesthetics with conversion optimisation and SEO.',
    benefits: [
      { icon: '🎨', title: 'Premium Design', desc: 'Custom-designed websites that reflect your brand and impress visitors.' },
      { icon: '⚡', title: 'Lightning Fast', desc: 'Optimised for speed — because slow sites lose customers and rankings.' },
      { icon: '📱', title: 'Mobile-First', desc: 'Perfect on every device — from smartphones to 4K monitors.' },
      { icon: '🔍', title: 'SEO-Ready', desc: 'Built with SEO best practices baked in from day one.' },
      { icon: '🎯', title: 'Conversion-Focused', desc: 'Strategic CTAs, social proof and UX design to maximise leads.' },
      { icon: '🔧', title: 'Easy to Manage', desc: 'CMS-powered so you can update content without touching code.' },
    ],
    includes: [
      'Custom UI/UX design',
      'Mobile-responsive development',
      'SEO-optimised code structure',
      'Page speed optimisation',
      'Contact forms & lead capture',
      'Google Analytics 4 & GTM integration',
      'Basic on-page SEO setup',
      '30 days post-launch support',
    ],
    process: [
      { step: '01', title: 'Discovery', desc: 'Understand your brand, goals and target audience.' },
      { step: '02', title: 'Design', desc: 'Create wireframes, then high-fidelity mockups for review.' },
      { step: '03', title: 'Develop', desc: 'Build the site with clean code and performance in mind.' },
      { step: '04', title: 'Launch', desc: 'Test, optimise and go live with full handover.' },
    ],
    tools: ['Figma', 'WordPress', 'Webflow', 'Next.js', 'Tailwind CSS', 'Adobe XD', 'GTmetrix'],
    faqs: [
      { q: 'How long does a website redesign take?', a: 'Typically 4–8 weeks depending on the size and complexity of the project. We provide a clear timeline before starting.' },
      { q: 'Will my new website be SEO-friendly?', a: 'Yes. Every website we build follows SEO best practices — proper heading structure, meta tags, schema markup, fast load times and mobile responsiveness.' },
    ],
    relatedServices: [
      { label: 'Website Development', href: '/services/website-development' },
      { label: 'WordPress Development', href: '/services/wordpress-development' },
      { label: 'Landing Page Design', href: '/services/landing-page-design' },
      { label: 'SEO Services', href: '/services/seo' },
    ],
  },
  'website-development': {
    slug: 'website-development',
    title: 'Website Development Services',
    headline: 'Custom Website Development Built for Performance & Scale',
    subheadline: 'We build fast, secure and scalable websites using modern technologies. Whether you need a custom web app or a powerful CMS — we deliver it.',
    description: 'Custom website development services using modern frameworks for businesses that need performance and scalability.',
    benefits: [
      { icon: '🚀', title: 'High Performance', desc: 'Built on Next.js / React for sub-second load times and 95+ Lighthouse scores.' },
      { icon: '🔒', title: 'Security-First', desc: 'Best-practice security implementation to protect your site and data.' },
      { icon: '📈', title: 'Scalable Architecture', desc: 'Built to grow — handle more traffic, features and complexity over time.' },
      { icon: '🔌', title: 'API Integrations', desc: 'Connect CRMs, payment gateways, analytics and any third-party tool.' },
      { icon: '🧩', title: 'Custom Features', desc: 'Whatever you need — booking systems, portals, dashboards — we build it.' },
      { icon: '📱', title: 'Cross-Device', desc: 'Perfect performance on desktop, tablet and mobile.' },
    ],
    includes: [
      'Custom front-end development (React / Next.js)',
      'Backend development (Node.js / PHP)',
      'Database design & optimisation',
      'REST API / GraphQL development',
      'CMS integration (WordPress / Sanity / Contentful)',
      'Payment gateway integration',
      'Performance & load testing',
      'Deployment & hosting setup',
    ],
    process: [
      { step: '01', title: 'Scoping', desc: 'Define requirements, tech stack and project timeline.' },
      { step: '02', title: 'Architecture', desc: 'Design database schema, API structure and component architecture.' },
      { step: '03', title: 'Development', desc: 'Agile development with regular demos and feedback loops.' },
      { step: '04', title: 'Deploy & Support', desc: 'Deploy to production with comprehensive testing and support.' },
    ],
    tools: ['Next.js', 'React', 'Node.js', 'WordPress', 'Vercel', 'AWS', 'PostgreSQL', 'Tailwind CSS', 'TypeScript'],
    faqs: [
      { q: 'What technologies do you use?', a: 'We primarily use Next.js, React, TypeScript and Tailwind CSS for the front end. For the back end we use Node.js or PHP / WordPress. The stack depends on your specific requirements.' },
    ],
    relatedServices: [
      { label: 'Website Design', href: '/services/website-design' },
      { label: 'WordPress Development', href: '/services/wordpress-development' },
      { label: 'Shopify Development', href: '/services/shopify-development' },
    ],
  },
  'wordpress-development': {
    slug: 'wordpress-development',
    title: 'WordPress Development Services',
    headline: 'Professional WordPress Development for Powerful, Easy-to-Manage Websites',
    subheadline: 'Custom WordPress websites that are fast, secure and built to rank on Google — with an intuitive CMS you can manage yourself.',
    description: 'Custom WordPress development services for businesses that need powerful, SEO-friendly and easy-to-manage websites.',
    benefits: [
      { icon: '🔧', title: 'Easy to Manage', desc: 'Update your content, add blog posts and manage pages without any coding knowledge.' },
      { icon: '🔌', title: '60,000+ Plugins', desc: 'Extend functionality with the world\'s largest plugin ecosystem.' },
      { icon: '⚡', title: 'Optimised for Speed', desc: 'We strip out bloated themes and build lean, fast WordPress sites.' },
      { icon: '🔒', title: 'Hardened Security', desc: 'Security-first WordPress setup with proper hardening, backups and updates.' },
      { icon: '🔍', title: 'SEO-Friendly', desc: 'Yoast SEO, schema markup, clean URLs and optimised code for better rankings.' },
      { icon: '📱', title: 'Fully Responsive', desc: 'Custom mobile-responsive themes tailored to your brand.' },
    ],
    includes: [
      'Custom WordPress theme development',
      'Plugin selection, setup & configuration',
      'Page builder integration (Gutenberg / Elementor)',
      'WooCommerce setup (if e-commerce)',
      'SEO plugin configuration',
      'Security hardening',
      'Speed optimisation',
      'CMS training & documentation',
    ],
    process: [
      { step: '01', title: 'Design', desc: 'Custom design mockups tailored to your brand.' },
      { step: '02', title: 'Theme Dev', desc: 'Build a custom WordPress theme from the design.' },
      { step: '03', title: 'Content & Plugins', desc: 'Set up all pages, plugins and functionality.' },
      { step: '04', title: 'Launch', desc: 'Launch, train you on the CMS and hand over.' },
    ],
    tools: ['WordPress', 'Elementor', 'ACF', 'Yoast SEO', 'WooCommerce', 'WP Rocket', 'Cloudflare'],
    faqs: [
      { q: 'Will I be able to manage my own WordPress site?', a: 'Yes. We build with ease-of-management in mind and provide full CMS training so you can update content, add blog posts and make changes without any developer help.' },
    ],
    relatedServices: [
      { label: 'Website Design', href: '/services/website-design' },
      { label: 'Shopify Development', href: '/services/shopify-development' },
      { label: 'SEO Services', href: '/services/seo' },
    ],
  },
  'shopify-development': {
    slug: 'shopify-development',
    title: 'Shopify Development Services',
    headline: 'Shopify Development That Builds High-Converting Online Stores',
    subheadline: 'Custom Shopify stores designed to sell. From theme customisation to full custom builds — we create e-commerce experiences that drive revenue.',
    description: 'Professional Shopify development services for brands that want beautiful, fast and high-converting e-commerce stores.',
    benefits: [
      { icon: '💸', title: 'Conversion-Optimised', desc: 'Every element designed to reduce friction and turn visitors into buyers.' },
      { icon: '⚡', title: 'Blazing Fast', desc: 'Optimised Shopify stores that pass Core Web Vitals and load in under 2 seconds.' },
      { icon: '🎨', title: 'Brand-Perfect Design', desc: 'Unique Shopify themes that reflect your brand identity and stand out.' },
      { icon: '📱', title: 'Mobile Commerce Ready', desc: '70%+ of e-commerce traffic is mobile. We optimise every touchpoint.' },
      { icon: '🔌', title: 'App Integrations', desc: 'Klaviyo, Judge.me, ReConvert, Yotpo and more — all set up correctly.' },
      { icon: '📦', title: 'Multi-Currency/Language', desc: 'Sell globally with Shopify Markets, multi-currency and translations.' },
    ],
    includes: [
      'Custom Shopify theme development / customisation',
      'Product & collection page optimisation',
      'Cart, checkout & post-purchase optimisation',
      'Shopify app integrations',
      'Klaviyo email automation setup',
      'Shopify SEO setup',
      'Payment & shipping configuration',
      'Speed optimisation',
    ],
    process: [
      { step: '01', title: 'Strategy', desc: 'Define store structure, product taxonomy and conversion goals.' },
      { step: '02', title: 'Design', desc: 'Create custom theme design or customise an existing theme.' },
      { step: '03', title: 'Build', desc: 'Develop, configure apps and populate products.' },
      { step: '04', title: 'Launch', desc: 'QA testing, speed optimisation and go-live.' },
    ],
    tools: ['Shopify', 'Shopify Liquid', 'Klaviyo', 'Judge.me', 'Yotpo', 'ReConvert', 'TailwindCSS'],
    faqs: [
      { q: 'Should I use Shopify for my online store?', a: 'Shopify is the best platform for most e-commerce businesses. It\'s fast, secure, scales easily and has a massive app ecosystem. We can help you decide if it\'s the right fit.' },
    ],
    relatedServices: [
      { label: 'E-commerce SEO', href: '/services/ecommerce-seo' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Website Design', href: '/services/website-design' },
    ],
  },
  'landing-page-design': {
    slug: 'landing-page-design',
    title: 'Landing Page Design Services',
    headline: 'High-Converting Landing Pages That Turn Clicks Into Customers',
    subheadline: 'Purpose-built landing pages optimised for your specific campaign goal — more leads, more sales, lower cost per conversion.',
    description: 'Professional landing page design and development focused on conversion rate optimisation.',
    benefits: [
      { icon: '🎯', title: 'Single-Goal Focus', desc: 'Distraction-free design that guides visitors toward one clear action.' },
      { icon: '💰', title: 'Lower Cost Per Lead', desc: 'Better landing pages mean higher Quality Scores and lower CPCs in Google Ads.' },
      { icon: '🔬', title: 'A/B Testing Ready', desc: 'Built with testing in mind so you can continuously improve conversion rates.' },
      { icon: '⚡', title: 'Fast Loading', desc: 'Optimised for speed — slow landing pages kill conversions.' },
      { icon: '📊', title: 'Conversion Tracking', desc: 'Full GA4 and GTM tracking so you know exactly what\'s converting.' },
      { icon: '🎨', title: 'On-Brand Design', desc: 'Professionally designed to match your brand and instil trust.' },
    ],
    includes: [
      'Custom landing page design (Figma)',
      'Responsive development',
      'Lead capture form integration',
      'Conversion tracking setup',
      'A/B test variant creation',
      'Page speed optimisation',
      'Thank you page design',
      'CRM / email integration',
    ],
    process: [
      { step: '01', title: 'Brief', desc: 'Understand the campaign goal, audience and offer.' },
      { step: '02', title: 'Design', desc: 'Wireframe and high-fidelity design with CRO principles.' },
      { step: '03', title: 'Build', desc: 'Fast, responsive development with tracking.' },
      { step: '04', title: 'Test', desc: 'Launch, A/B test and optimise.' },
    ],
    tools: ['Figma', 'Webflow', 'Next.js', 'Unbounce', 'Google Tag Manager', 'Hotjar', 'Google Optimize'],
    faqs: [
      { q: 'What is a landing page?', a: 'A landing page is a standalone web page created for a specific marketing campaign. Unlike your homepage, it has one goal: get the visitor to take a specific action (sign up, buy, call, etc.).' },
    ],
    relatedServices: [
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'CRO', href: '/services/cro' },
      { label: 'Website Design', href: '/services/website-design' },
    ],
  },
  cro: {
    slug: 'cro',
    title: 'Conversion Rate Optimisation (CRO)',
    headline: 'CRO Services That Make Your Existing Traffic Worth More',
    subheadline: 'Double your revenue without doubling your ad spend. We optimise your website to convert a higher percentage of visitors into leads and customers.',
    description: 'Conversion rate optimisation services using data analysis, A/B testing and UX improvements.',
    benefits: [
      { icon: '💰', title: 'More Revenue, Same Traffic', desc: 'Increasing your conversion rate from 1% to 2% doubles your revenue without more ad spend.' },
      { icon: '🔬', title: 'Data-Backed Decisions', desc: 'We use heatmaps, session recordings and analytics to diagnose and fix issues.' },
      { icon: '🧪', title: 'A/B Testing', desc: 'Systematic testing of headlines, CTAs, layouts and more to find what converts best.' },
      { icon: '📊', title: 'Measurable Results', desc: 'Clear before/after conversion rate reporting with revenue impact.' },
      { icon: '🎯', title: 'Funnel Optimisation', desc: 'Fix leaks at every stage of your sales funnel — awareness to purchase.' },
      { icon: '😊', title: 'Better User Experience', desc: 'CRO improvements also create better experiences that build trust and loyalty.' },
    ],
    includes: [
      'Conversion audit & funnel analysis',
      'Heatmap & session recording analysis',
      'User journey mapping',
      'A/B test planning and execution',
      'Landing page & checkout optimisation',
      'Form optimisation',
      'Trust element & social proof recommendations',
      'Monthly CRO reporting',
    ],
    process: [
      { step: '01', title: 'Audit', desc: 'Analyse your funnel, heatmaps and user behaviour.' },
      { step: '02', title: 'Hypothesise', desc: 'Form data-backed hypotheses for what to test.' },
      { step: '03', title: 'Test', desc: 'Run A/B tests with statistical significance.' },
      { step: '04', title: 'Implement', desc: 'Roll out winners and continue the testing cycle.' },
    ],
    tools: ['Google Optimize', 'VWO', 'Hotjar', 'Crazy Egg', 'Google Analytics 4', 'FullStory'],
    faqs: [
      { q: 'What is a good conversion rate?', a: 'The average website conversion rate is 2–3%. A good CRO programme aims to beat your industry benchmark. We\'ll audit your current rate and set realistic improvement targets.' },
    ],
    relatedServices: [
      { label: 'Landing Page Design', href: '/services/landing-page-design' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Website Design', href: '/services/website-design' },
    ],
  },
  orm: {
    slug: 'orm',
    title: 'Online Reputation Management (ORM)',
    headline: 'Protect & Build Your Online Reputation with Expert ORM',
    subheadline: 'Your reputation is your most valuable asset. We monitor, manage and improve what people find when they search for your brand online.',
    description: 'Online reputation management services to monitor, protect and enhance your brand\'s online presence.',
    benefits: [
      { icon: '⭐', title: 'More 5-Star Reviews', desc: 'Proactive review generation strategy to build a strong positive review profile.' },
      { icon: '🛡️', title: 'Negative Review Response', desc: 'Professional, brand-safe responses to negative reviews that turn critics into fans.' },
      { icon: '🔍', title: 'SERP Reputation Control', desc: 'Push positive content to the top of Google to bury negative results.' },
      { icon: '📊', title: 'Brand Monitoring', desc: '24/7 monitoring of all mentions of your brand across the web.' },
      { icon: '🤝', title: 'Trust Building', desc: 'A strong online reputation directly impacts conversion rates and purchasing decisions.' },
      { icon: '🚨', title: 'Crisis Management', desc: 'Fast, strategic response to reputation crises to minimise damage.' },
    ],
    includes: [
      'Brand monitoring setup (Google Alerts, Mention.com)',
      'Review audit across Google, Trustpilot, Just Dial etc.',
      'Review generation strategy & outreach templates',
      'Negative review response management',
      'Positive content creation & promotion',
      'Wikipedia monitoring (if applicable)',
      'Monthly ORM reporting',
    ],
    process: [
      { step: '01', title: 'Audit', desc: 'Full audit of your current online reputation and review profiles.' },
      { step: '02', title: 'Strategy', desc: 'Custom ORM strategy based on your specific situation and goals.' },
      { step: '03', title: 'Execute', desc: 'Implement review generation, content and monitoring.' },
      { step: '04', title: 'Monitor', desc: 'Ongoing monitoring and monthly reputation reporting.' },
    ],
    tools: ['Google Alerts', 'Mention.com', 'BrightLocal', 'ReviewTrackers', 'Trustpilot'],
    faqs: [
      { q: 'Can negative reviews be removed?', a: 'Only reviews that violate platform policies can be officially removed. However, we can respond professionally to negative reviews and generate a high volume of positive reviews to minimise their impact.' },
    ],
    relatedServices: [
      { label: 'Local SEO', href: '/services/local-seo' },
      { label: 'Content Marketing', href: '/services/content-marketing' },
      { label: 'Social Media Marketing', href: '/services/social-media-marketing' },
    ],
  },
  'email-marketing': {
    slug: 'email-marketing',
    title: 'Email Marketing Services',
    headline: 'Email Marketing That Nurtures Leads & Drives Repeat Revenue',
    subheadline: 'Email delivers ₹3,600 for every ₹100 spent. Our expert email marketing service builds and automates campaigns that convert prospects into customers and customers into fans.',
    description: 'Full-service email marketing including strategy, list building, automation and campaign management.',
    benefits: [
      { icon: '📧', title: 'Highest ROI Channel', desc: 'Email marketing consistently delivers the highest ROI of any digital channel.' },
      { icon: '🔄', title: 'Marketing Automation', desc: 'Set-and-forget automations that nurture leads 24/7 without manual effort.' },
      { icon: '🎯', title: 'Segmentation & Personalisation', desc: 'The right message to the right person at the right time.' },
      { icon: '🛒', title: 'Abandoned Cart Recovery', desc: 'Recover lost sales with automated abandoned cart email sequences.' },
      { icon: '📊', title: 'Full Analytics', desc: 'Open rates, click rates, revenue tracking — you know exactly what\'s working.' },
      { icon: '🔒', title: 'You Own Your List', desc: 'Unlike social media, your email list is an asset you own and control.' },
    ],
    includes: [
      'Email marketing strategy & audit',
      'ESP setup & integration (Klaviyo / Mailchimp / ActiveCampaign)',
      'List cleaning & segmentation',
      'Welcome sequence automation',
      'Abandoned cart sequence (e-commerce)',
      'Monthly newsletter design & copywriting',
      'A/B testing (subject lines, CTAs)',
      'Monthly performance reporting',
    ],
    process: [
      { step: '01', title: 'Audit', desc: 'Review your current email setup, deliverability and automation gaps.' },
      { step: '02', title: 'Strategy', desc: 'Build a full email marketing strategy and automation map.' },
      { step: '03', title: 'Build', desc: 'Design templates, write sequences and set up automations.' },
      { step: '04', title: 'Optimise', desc: 'A/B test and optimise based on engagement data.' },
    ],
    tools: ['Klaviyo', 'Mailchimp', 'ActiveCampaign', 'Brevo', 'HubSpot', 'ConvertKit', 'Litmus'],
    faqs: [
      { q: 'Which email platform do you use?', a: 'We work with Klaviyo, Mailchimp, ActiveCampaign, HubSpot and more. We\'ll recommend the best platform for your business size, goals and budget.' },
    ],
    relatedServices: [
      { label: 'Content Marketing', href: '/services/content-marketing' },
      { label: 'Lead Generation', href: '/services/lead-generation' },
      { label: 'CRO', href: '/services/cro' },
    ],
  },
  'lead-generation': {
    slug: 'lead-generation',
    title: 'Lead Generation Services',
    headline: 'Lead Generation Services That Fill Your Sales Pipeline',
    subheadline: 'Stop chasing cold prospects. We build multi-channel lead generation systems that attract qualified, ready-to-buy leads consistently.',
    description: 'Multi-channel lead generation services combining SEO, PPC, social ads and landing pages.',
    benefits: [
      { icon: '🎯', title: 'Qualified Leads Only', desc: 'We target people who are actively looking for what you offer — not cold traffic.' },
      { icon: '📈', title: 'Predictable Pipeline', desc: 'A reliable, scalable system that generates leads month after month.' },
      { icon: '🔄', title: 'Multi-Channel Approach', desc: 'SEO, PPC, social ads, email — we use every channel that works for your business.' },
      { icon: '📊', title: 'Cost Per Lead Tracking', desc: 'Clear visibility on your CPL across every channel.' },
      { icon: '🤝', title: 'CRM Integration', desc: 'Leads flow directly into your CRM with full source tracking.' },
      { icon: '⚡', title: 'Quick Results', desc: 'Paid lead generation can start producing leads within days of launch.' },
    ],
    includes: [
      'Lead generation strategy & channel mix',
      'Landing page design & development',
      'Google Ads / Facebook Ads setup',
      'Lead magnet creation',
      'CRM integration & lead routing',
      'Conversion tracking setup',
      'Lead nurturing email sequence',
      'Monthly lead gen reporting',
    ],
    process: [
      { step: '01', title: 'ICP Definition', desc: 'Define your ideal customer profile and target segments.' },
      { step: '02', title: 'Channel Strategy', desc: 'Identify the best channels to reach your ICP.' },
      { step: '03', title: 'Build & Launch', desc: 'Build landing pages, set up ads and launch campaigns.' },
      { step: '04', title: 'Optimise & Scale', desc: 'Reduce CPL and scale what\'s working.' },
    ],
    tools: ['Google Ads', 'Meta Ads Manager', 'HubSpot', 'Salesforce', 'ActiveCampaign', 'Zapier', 'Hotjar'],
    faqs: [
      { q: 'How quickly can I start getting leads?', a: 'With paid channels (Google Ads, Meta Ads), you can start receiving leads within 3–5 days of launch. Organic channels (SEO) take longer but deliver lower-cost leads over time.' },
    ],
    relatedServices: [
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Landing Page Design', href: '/services/landing-page-design' },
      { label: 'Email Marketing', href: '/services/email-marketing' },
    ],
  },
  branding: {
    slug: 'branding',
    title: 'Branding Services',
    headline: 'Branding Services That Build Unforgettable Business Identities',
    subheadline: 'Your brand is more than a logo. We create cohesive brand identities that communicate your values, build trust and make you memorable.',
    description: 'Professional branding services including logo design, brand identity, brand guidelines and brand strategy.',
    benefits: [
      { icon: '🎨', title: 'Stand Out', desc: 'A distinctive brand identity that sets you apart from every competitor.' },
      { icon: '🤝', title: 'Build Trust', desc: 'Professional branding signals credibility and makes customers confident in choosing you.' },
      { icon: '💡', title: 'Brand Consistency', desc: 'Cohesive brand guidelines ensure consistent presentation across all touchpoints.' },
      { icon: '❤️', title: 'Emotional Connection', desc: 'A brand that resonates emotionally drives loyalty and word-of-mouth.' },
      { icon: '💰', title: 'Command Premium Pricing', desc: 'Strong brands can charge more. Brand equity directly impacts revenue.' },
      { icon: '🔮', title: 'Long-Term Asset', desc: 'A great brand is one of the most valuable long-term business assets you can build.' },
    ],
    includes: [
      'Brand discovery & strategy session',
      'Logo design (3 concepts + revisions)',
      'Brand colour palette & typography',
      'Business card & letterhead design',
      'Social media branding kit',
      'Brand guidelines document',
      'Email signature design',
      'Brand asset library (all file formats)',
    ],
    process: [
      { step: '01', title: 'Discovery', desc: 'Deep dive into your business, audience and competitive landscape.' },
      { step: '02', title: 'Strategy', desc: 'Define brand positioning, personality and messaging.' },
      { step: '03', title: 'Design', desc: 'Create visual identity concepts for review.' },
      { step: '04', title: 'Deliver', desc: 'Finalise brand guidelines and deliver all assets.' },
    ],
    tools: ['Adobe Illustrator', 'Adobe Photoshop', 'Figma', 'Adobe InDesign'],
    faqs: [
      { q: 'How many logo concepts do I get?', a: 'We provide 3 initial logo concepts. After your feedback, we proceed with one direction and provide unlimited minor revisions until you\'re completely satisfied.' },
    ],
    relatedServices: [
      { label: 'Website Design', href: '/services/website-design' },
      { label: 'Social Media Marketing', href: '/services/social-media-marketing' },
      { label: 'Content Marketing', href: '/services/content-marketing' },
    ],
  },
  'digital-marketing-consulting': {
    slug: 'digital-marketing-consulting',
    title: 'Digital Marketing Consulting',
    headline: 'Digital Marketing Consulting for Businesses Ready to Scale',
    subheadline: 'Get expert strategic guidance from experienced digital marketing consultants who have helped 1,000+ businesses grow. Perfect for in-house teams that need direction.',
    description: 'Expert digital marketing consulting and strategy sessions for businesses that need guidance and a clear growth roadmap.',
    benefits: [
      { icon: '🧭', title: 'Clear Direction', desc: 'A custom digital marketing roadmap tailored to your business goals and budget.' },
      { icon: '💡', title: 'Expert Perspective', desc: 'Benefit from 7+ years of experience across industries and channels.' },
      { icon: '🔍', title: 'Honest Audit', desc: 'We tell you exactly what\'s working, what\'s not, and what to prioritise.' },
      { icon: '⚡', title: 'Fast Results', desc: 'Consulting accelerates your team\'s learning curve and avoids costly mistakes.' },
      { icon: '🎯', title: 'Unbiased Advice', desc: 'We recommend what\'s best for your business — not what\'s most profitable for us.' },
      { icon: '🤝', title: 'In-House Team Training', desc: 'Upskill your internal marketing team with hands-on training sessions.' },
    ],
    includes: [
      '2-hour strategy session',
      'Full digital marketing audit',
      'Custom growth roadmap (90-day plan)',
      'Channel prioritisation recommendations',
      'Budget allocation guidance',
      'Toolstack recommendations',
      'Team training sessions (optional)',
      'Follow-up Q&A session',
    ],
    process: [
      { step: '01', title: 'Brief', desc: 'Understand your business, goals and current challenges.' },
      { step: '02', title: 'Audit', desc: 'Deep-dive into your current digital marketing performance.' },
      { step: '03', title: 'Strategy', desc: 'Build a prioritised roadmap with clear action items.' },
      { step: '04', title: 'Present', desc: 'Present findings, recommendations and answer all questions.' },
    ],
    faqs: [
      { q: 'Who is digital marketing consulting best for?', a: 'Consulting works best for businesses with an in-house team that needs strategic direction, businesses evaluating their current agency, or companies planning a major digital marketing investment.' },
    ],
    relatedServices: [
      { label: 'SEO Services', href: '/services/seo' },
      { label: 'Google Ads', href: '/services/google-ads' },
      { label: 'Content Marketing', href: '/services/content-marketing' },
    ],
  },
}

export function getServiceData(slug: string): ServiceData | null {
  return servicesData[slug] ?? null
}

export function getServiceBreadcrumbs(slug: string, title: string) {
  return [
    { name: 'Home', href: siteConfig.url },
    { name: 'Services', href: `${siteConfig.url}/services` },
    { name: title, href: `${siteConfig.url}/services/${slug}` },
  ]
}
